apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend

spec:
  replicas: 2

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
      - name: frontend
        image: 540191526881.dkr.ecr.us-east-1.amazonaws.com/frontend:128
        ports:
        - containerPort: 80

        # env:
        # - name: REACT_APP_API_BASE_URL
        #   value: "http://your-backend-load-balancer-url"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend

spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP

  # nodePort: 31004

  selector:
    app: frontend

  type: LoadBalancer
